services:
  tdc_frontend:
    build: ./frontend
    container_name: tdc_frontend
    restart: unless-stopped

    # ---------- LINUX profile ----------
    profiles: ["linux"]
    environment:
      - DISPLAY=${DISPLAY}
      - TZ=America/New_York
    volumes:
      - ${XDG_RUNTIME_DIR:-/tmp}/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host          # LAN speed & multicast discovery

  tdc_frontend_novnc:
    extends: tdc_frontend       # same image
    profiles: ["windows"]
    environment:
      - USE_NOVNC=1             # triggers headless mode
      - TZ=America/New_York
      - BACKEND_URL=http://<BACKEND_IP>:8000
    ports:
      - "6080:6080"             # web VNC
    volumes: []                 # no X-socket
